# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

@daftpunk = Artist.create(name: "Daft Punk", artist_image_url: "http://cdn.pastemagazine.com/www/articles/daftpunk2.jpg")
@random_access_memories = Album.create(name: "Random Access Memories", artist: @daftpunk, album_url: "https://upload.wikimedia.org/wikipedia/en/a/a7/Random_Access_Memories.jpg")
@give_life_back_to_music = Song.create(name: "Give Life Back to Music", album: @random_access_memories)
@the_game_of_love = Song.create(name: "The Game of Love", album: @random_access_memories)
@giorgio_by_moroder = Song.create(name: "Giorgio by Moroder" , album: @random_access_memories)
@within = Song.create(name: "Within", album: @random_access_memories)
@instant_crush = Song.create(name: "Instant Crush", album: @random_access_memories)
@lose_yourself_to_dance = Song.create(name: "Lose Yourself to Dance", album: @random_access_memories)
@touch = Song.create(name: "Touch", album: @random_access_memories)
@get_lucky = Song.create(name: "Get Lucky", album: @random_access_memories)
@beyond = Song.create(name: "Beyond", album: @random_access_memories)
@motherboard = Song.create(name: "Motherboard", album: @random_access_memories)
@fragments_of_time = Song.create(name: "Fragments of Time", album: @random_access_memories)
@doin_it_right = Song.create(name: "Doin' It Right", album: @random_access_memories)
@contact = Song.create(name: "Contact", album: @random_access_memories)

@beyonce = Artist.create(name: "Beyoncé", artist_image_url: "https://a1-images.myspacecdn.com/images04/2/2a979ebc42d741a7903a1cbcf9b26f34/300x300.jpg")
@lemonade = Album.create(name: "Lemonade", artist: @beyonce, album_url: "https://upload.wikimedia.org/wikipedia/en/5/53/Beyonce_-_Lemonade_%28Official_Album_Cover%29.png")
@pray_you_catch_me = Song.create(name: "Pray You Catch Me", album: @lemonade)
@hold_up = Song.create(name: "Hold Up", album: @lemonade)
@dont_hurt_yourself = Song.create(name: "Don't Hurt Yourself", album: @lemonade)
@sorry = Song.create(name: "Sorry", album: @lemonade)
@six_inch = Song.create(name: "6 Inch", album: @lemonade)
@daddy_lessons = Song.create(name: "Daddy Lessons", album: @lemonade)
@love_drought = Song.create(name: "Love Drought", album: @lemonade)
@sandcastles = Song.create(name: "Sandcastles", album: @lemonade)
@forward = Song.create(name: "Forward", album: @lemonade)
@freedom = Song.create(name: "Freedom", album: @lemonade)
@all_night = Song.create(name: "All Night", album: @lemonade)
@formation = Song.create(name: "Formation", album: @lemonade)

@radiohead = Artist.create(name: "Radiohead", artist_image_url: "http://assets.rollingstone.com/assets/images/artists/radiohead.jpg")
@a_moon_shaped_pool = Album.create(name: "A Moon Shaped Pool", artist: @radiohead, album_url: "https://upload.wikimedia.org/wikipedia/en/c/c1/A_Moon_Shaped_Pool.jpg")
@burn_the_witch = Song.create(name: "Burn the Witch", album: @a_moon_shaped_pool)
@daydreaming = Song.create(name: "Daydreaming", album: @a_moon_shaped_pool)
@decks_dark = Song.create(name: "Decks Dark", album: @a_moon_shaped_pool)
@desert_island_disk = Song.create(name: "Desert Island Disk", album: @a_moon_shaped_pool)
@full_stop = Song.create(name: "Ful Stop", album: @a_moon_shaped_pool)
@glass_eyes = Song.create(name: "Glass Eyes", album: @a_moon_shaped_pool)
@identikit = Song.create(name: "Identikit", album: @a_moon_shaped_pool)
@the_numbers = Song.create(name: "The Numbers", album: @a_moon_shaped_pool)
@present_tense = Song.create(name: "Present Tense", album: @a_moon_shaped_pool)
@tink_tailor = Song.create(name: "Tinker Tailor Soldier Sailor Rich Man Poor Man Beggar Man Thief", album: @a_moon_shaped_pool)
@true_love_waits = Song.create(name: "True Love Waits", album: @a_moon_shaped_pool)

@kendrick_lamar = Artist.create(name: "Kendrick Lamar", artist_image_url: "http://artcreationforever.com/images/kendrick-lamar/kendrick-lamar-06.jpg")
@to_pimp_a_butterfly = Album.create(name: "To Pimp a Butterfly", artist: @kendrick_lamar, album_url: "https://upload.wikimedia.org/wikipedia/en/f/f6/Kendrick_Lamar_-_To_Pimp_a_Butterfly.png")
@wesleys_theory = Song.create(name: "Wesley's Theory", album: @to_pimp_a_butterfly)
@for_free = Song.create(name: "For Free? (Interlude)", album: @to_pimp_a_butterfly)
@king_kunta = Song.create(name: "King Kunta", album: @to_pimp_a_butterfly)
@institutionalized = Song.create(name: "Institutionalized", album: @to_pimp_a_butterfly)
@these_walls = Song.create(name: "These Walls", album: @to_pimp_a_butterfly)
@u = Song.create(name: "u", album: @to_pimp_a_butterfly)
@alright = Song.create(name: "Alright", album: @to_pimp_a_butterfly)
@for_sale = Song.create(name: "For Sale? (Interlude)", album: @to_pimp_a_butterfly)
@momma = Song.create(name: "Momma", album: @to_pimp_a_butterfly)
@hood_politics = Song.create(name: "Hood Politics", album: @to_pimp_a_butterfly)
@how_much = Song.create(name: "How Much a Dollar Cost", album: @to_pimp_a_butterfly)
@complexion = Song.create(name: "Complexion (A Zulu Love)", album: @to_pimp_a_butterfly)
@the_blacker_they_berry = Song.create(name: "The Blacker the Berry", album: @to_pimp_a_butterfly)
@you_aint_gotta_life = Song.create(name: "You Ain't Gotta Lie (Momma Said)", album: @to_pimp_a_butterfly)
@i = Song.create(name: "i", album: @to_pimp_a_butterfly)
@mortal_man = Song.create(name: "Mortal Man", album: @to_pimp_a_butterfly)

 